dados = list()
pessoas = list()
dados.append('Edyvaldo Coelho')
dados.append(21)
pessoas.append(dados[:])
dados.append('Jesuina')
dados.append(19)
pessoas.append(dados[:])
dados.append('Priscila')
dados.append(20)