number = int(input('Qual é o número que queres ver a tabuada? '))
print('A tabuada do número {} é:'.format(number))
print('='*20)
print('{} * 1  = {:<2}'.format(number, number))
print('{} * 2  = {:<2}'.format(number, number * 2))
print('{} * 3  = {:<2}'.format(number, number * 3))
print('{} * 4  = {:<2}'.format(number, number * 4))
print('{} * 5  = {:<2}'.format(number, number * 5))
print('{} * 6  = {:<2}'.format(number, number * 6))
print('{} * 7  = {:<2}'.format(number, number * 7))
print('{} * 8  = {:<2}'.format(number, number * 8))
print('{} * 9  = {:<2}'.format(number, number * 9))
print('{} * 10 = {:<2}'.format(number, number * 10))
print('{} * 11 = {:<2}'.format(number, number * 11))
print('{} * 12 = {:<2}'.format(number, number * 12))
print('='*20)