valor = input('Digite um algo: ')
print('\n O que digitaste é')
print('O valor é do tipo: \033[34m{}\033[m'.format(type(valor)))
print('É composto apenas de números: \033[34m{}\033[m'.format(valor.isnumeric()))
print('É composto apenas de letras: \033[34m{}\033[m'.format(valor.isalpha()))
print('É composto por letras e números: \033[34m{}\033[m'.format(valor.isalnum()))
print('É composto só por letras maiusculas: \033[34m{}\033[m'.format(valor.isupper()))
print('É composto só por letras minusculas: \033[34m{}\033[m'.format(valor.islower()))
print('O valor é apenas espaço: \033[34m{}\033[m\n'.format(valor.isspace()))
